spring:
  data:
    mongodb:
      database: demodatabase
      host: localhost
      port: 27017

eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
      
server:
  port: 8082