server:
  port: 8081
  servlet:
    context-path: /api/user
  tomcat:
    threads:
      max: 5
    
spring:
  application:
    name: user-service
  datasource:
    password: '@root@123321'
    url: jdbc:mysql://localhost:3306/demodatabase
    username: root
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
  endpoint:
    health:
      show-details: ALWAYS
       
  
resilience4j:
  circuitbreaker:
    instances:
      hotelserviceBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
  bulkhead:
    instances:
      hotelserviceBulkhead:
        maxConcurrentCalls: 5
        maxWaitDuration: 10ms
  
  
        
  